# Generated by Django 4.0.2 on 2022-03-08 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=0, max_length=20)),
                ('medicine_name', models.CharField(default='Medicine', max_length=100)),
                ('medicine_quantity', models.IntegerField(default=0)),
                ('donation_date', models.DateField(default=datetime.datetime(2022, 3, 8, 13, 17, 4, 40796))),
                ('expiry_date', models.DateField(default=datetime.datetime(2022, 3, 8, 13, 17, 4, 40796))),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=0, max_length=20)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicineStockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(default='Medicine', max_length=100)),
                ('medicine_quantity', models.IntegerField(default=0)),
                ('expiry_date', models.DateField(default=datetime.datetime(2022, 3, 8, 13, 17, 4, 56417))),
            ],
        ),
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=0, max_length=20)),
                ('medicine_name', models.CharField(default='Medicine', max_length=100)),
                ('medicine_quantity', models.IntegerField(default=0)),
                ('request_date', models.DateField(default=datetime.datetime(2022, 3, 8, 13, 17, 4, 40796))),
            ],
        ),
    ]
