# Generated by Django 4.0.3 on 2022-04-08 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmodel',
            name='donation_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 8, 12, 26, 35, 808021)),
        ),
        migrations.AlterField(
            model_name='donationmodel',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 8, 12, 26, 35, 808021)),
        ),
        migrations.AlterField(
            model_name='medicinestockmodel',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 8, 12, 26, 35, 808021)),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='request_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 8, 12, 26, 35, 808021)),
        ),
    ]
