# Generated by Django 4.0.3 on 2022-04-11 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_alter_donationmodel_donation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='address',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='medicinestockmodel',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 11, 22, 31, 54, 297373)),
        ),
    ]
