# Generated by Django 4.0.3 on 2022-04-11 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_alter_entry_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinestockmodel',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 11, 23, 22, 57, 288458)),
        ),
    ]
