# Generated by Django 4.0.3 on 2022-04-11 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_alter_medicinestockmodel_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationmodel',
            name='pickup_address',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='donationmodel',
            name='donation_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 11, 23, 23, 16, 551785)),
        ),
        migrations.AlterField(
            model_name='donationmodel',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 11, 23, 23, 16, 551785)),
        ),
        migrations.AlterField(
            model_name='medicinestockmodel',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 11, 23, 23, 16, 551785)),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='request_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 11, 23, 23, 16, 551785)),
        ),
    ]
