# Generated by Django 3.2.12 on 2022-03-10 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_alter_donationmodel_donation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmodel',
            name='donation_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 10, 10, 12, 46, 153260)),
        ),
        migrations.AlterField(
            model_name='donationmodel',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 10, 10, 12, 46, 153283)),
        ),
        migrations.AlterField(
            model_name='medicinestockmodel',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 10, 10, 12, 46, 154009)),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='request_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 10, 10, 12, 46, 153620)),
        ),
    ]
