# Generated by Django 4.0.3 on 2022-04-11 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_donationmodel_pickup_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmodel',
            name='donation_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 11, 23, 24, 53, 763284)),
        ),
        migrations.AlterField(
            model_name='donationmodel',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 11, 23, 24, 53, 763284)),
        ),
        migrations.AlterField(
            model_name='medicinestockmodel',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 11, 23, 24, 53, 763284)),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='request_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 11, 23, 24, 53, 763284)),
        ),
    ]
