# Generated by Django 4.0.3 on 2022-04-11 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0006_alter_donationmodel_donation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationmodel',
            name='phone_no',
            field=models.CharField(default='Not found', max_length=20),
        ),
        migrations.AlterField(
            model_name='donationmodel',
            name='donation_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='donationmodel',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='donationmodel',
            name='pickup_address',
            field=models.TextField(default='Not found'),
        ),
        migrations.AlterField(
            model_name='medicinestockmodel',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='request_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
