# Generated by Django 4.0.3 on 2022-04-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0008_alter_donationmodel_medicine_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='purpose',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='upload_file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
