# Generated by Django 4.0.3 on 2022-04-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0012_alter_entry_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmodel',
            name='upload_file',
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
