# Generated by Django 4.0.3 on 2022-04-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0014_alter_requestmodel_medicine_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
