# Generated by Django 4.0.3 on 2022-04-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0015_alter_requestmodel_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images2/'),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images1/'),
        ),
    ]
