# Generated by Django 4.0.3 on 2022-04-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0017_alter_entry_image_alter_requestmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
