# Generated by Django 4.0.3 on 2022-04-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0018_alter_entry_image_alter_requestmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmodel',
            name='medicine_quantity',
            field=models.IntegerField(default='0', max_length=300),
        ),
    ]
