# Generated by Django 4.0.3 on 2022-04-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0020_alter_requestmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activemembers',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
