# Generated by Django 4.0.1 on 2022-04-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0022_remove_feedbackmodel_id_medicinestockmodel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='medicine_quantity',
            field=models.IntegerField(max_length=50),
        ),
    ]
