# Generated by Django 4.0.1 on 2022-04-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0023_alter_requestmodel_medicine_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
