# Generated by Django 4.0.3 on 2022-04-13 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0023_alter_requestmodel_medicine_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='donationmodel',
            name='donation_date',
            field=models.DateField(default=datetime.date(2022, 4, 14)),
        ),
        migrations.AlterField(
            model_name='donationmodel',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2022, 4, 14)),
        ),
        migrations.AlterField(
            model_name='medicinestockmodel',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2022, 4, 14)),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='request_date',
            field=models.DateField(default=datetime.date(2022, 4, 14)),
        ),
    ]
