# Generated by Django 4.0.3 on 2022-04-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0031_alter_activemembers_image_alter_entry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activemembers',
            name='image',
            field=models.FileField(blank=True, default='profile/profile.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.FileField(blank=True, default='profile/profile.png', null=True, upload_to=''),
        ),
    ]
