# Generated by Django 4.0.3 on 2022-04-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0032_alter_activemembers_image_alter_entry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='prescription'),
        ),
    ]
