# Generated by Django 4.0.3 on 2022-04-16 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0034_alter_activemembers_image_alter_entry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmodel',
            name='donation_date',
            field=models.DateField(default=datetime.date(2022, 4, 16)),
        ),
        migrations.AlterField(
            model_name='donationmodel',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2022, 4, 16)),
        ),
        migrations.AlterField(
            model_name='donationmodel',
            name='status',
            field=models.CharField(default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='medicinestockmodel',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2022, 4, 16)),
        ),
        migrations.AlterField(
            model_name='medicinestockmodel',
            name='status',
            field=models.CharField(default='Usable', max_length=200),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='request_date',
            field=models.DateField(default=datetime.date(2022, 4, 16)),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='status',
            field=models.CharField(default='pending', max_length=200),
        ),
    ]
